remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
# Titel und Logo f端r dieses Theme
title: Rundgang Altstadt Frauenfeld
description: Diese Seite dient als Guide f端r den Rundgang durch die Stadt Frauenfeld, da sie 端ber eine Interaktive Karte verf端gt, auf welcher alle Punkte markiert sind und mit einer kurzen Beschreibung ausgestattet sind.
logo: ./https://github.com/ElioForster/altstadt/blob/main/IMG_4671.PNG

github:
  zip_url: http://Stadtrundgang_Frauenfeld.com/download.zip
